# Generated by Django 3.1.7 on 2021-03-10 20:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('courier_type', models.CharField(choices=[('foot', 'пеший курьер'), ('bike', 'велокурьер'), ('car', 'курьер на автомобиле')], max_length=10)),
                ('regions', models.JSONField(blank=True, null=True)),
                ('working_hours', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('weight', models.FloatField()),
                ('region', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('delivery_hours', models.JSONField()),
                ('completed', models.BooleanField(default=False)),
                ('assign_time', models.DateTimeField(blank=True, null=True)),
                ('complete_time', models.DateTimeField(blank=True, null=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.courier')),
            ],
        ),
    ]
